# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py
import os

link_handler("opera \"%u\"")
image_handler("feh \"%u\"", fetch=True)
keys[' '] = ["reader","toggle_show_links"]

add("http://rss.slashdot.org/Slashdot/slashdot", rate=20, keep=10, tags=["Slashdot"])
#add("http://www.facebook.com/feeds/notifications.php?id=100001514853154&viewer=100001514853154&key=21f07b733c&format=rss20", rate=5, keep=10, tags=["FB"])
